### ISSUE TITLE
alloy smelter mixin injection failure

### ISSUE THREAD

**Issue by justliliandev** [AlmostReliable/kubejs-enderio#1]
### Version

0.3.0

### Crash Report

https://pste.me/@R1eOG8SKEaA

### Additional Context

Yes

### Modifications

it's a bigger modpack, however, would you mind working with us to remove the mixin alltogether, I would much rather expose something in the api then have mixins target non api classes?

Reference: https://github.com/Team-EnderIO/EnderIO/issues/520

### Did the crash happen in singleplayer or on a server?

Both

**Comment by justliliandev** [comment]
This PR has been setup to remove the mixin: https://github.com/Team-EnderIO/EnderIO/pull/521

**Comment by Rover656** [comment]
The PR above has been merged and released in version 6.0.20-alpha. Thanks :)

**Comment by rlnt** [comment]
Understandable, thanks for the API endpoint.
