### ISSUE TITLE
Sagmilling method not working in script

### ISSUE THREAD

**Issue by AGUrGrill** [AlmostReliable/kubejs-enderio#3]
### Version

1.20.1-0.3.1

### Describe the bug!

I am currently trying to add sagmilling recipes, and they are not working. I have also tried the examples given, and they do not work either. TI am thinking maybe there was an update that broke it or I'm stupid, here is an example of what I'm trying to do that's not working:  

sagmilling(["gravel"], "aether:holystone",500); 
sagmilling(["enderio:powdered_coal"], "charcoal",500);

Other than that all the other recipe types have been working fine.

### Additional Context

Yes

### Modifications

A couple of mods, such as Aether and EnderIO.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
I made a pull request for EnderIO to make some of their recipe types more consistent. It's now called `sag_milling`. I didn't have time to update this in the wiki yet, sorry.

**Comment by AGUrGrill** [comment]
I just tried "sag_milling", and it is showing as not defined in the kube js error.
![image](https://github.com/AlmostReliable/kubejs-enderio/assets/48829902/01202fd7-8067-41ef-85f6-b8b68049cd6e)

Line with error: sag_milling(["gravel"], "aether:holystone",500);

**Comment by rlnt** [comment]
It's working for me. Please join the Discord. That's a bit easier to help you with that.

**Comment by Xplodin** [comment]
This error also appears on server
![image](https://github.com/AlmostReliable/kubejs-enderio/assets/13007677/20cd8d05-c85d-4236-910e-1a9d66cfab3d)

**Comment by rlnt** [comment]
Like the previous response should indicate, please join the Discord in order to receive support.
