### ISSUE TITLE
EnderIO 7 

### ISSUE THREAD

**Issue by azmrv** [AlmostReliable/kubejs-enderio#8]
### Describe the feature/addition!

add support for v7.0.8-alpha for Minecraft 1.21.1

### Why would like to see this feature/addition?

https://github.com/Team-EnderIO/EnderIO/releases/tag/v7.0.8-alpha
Most bugs are fixed in this version of EIO!

**Comment by rlnt** [comment]
Already in progress, it just needs some time because a ton of stuff changed.

**Comment by rlnt** [comment]
Pushing a release now, should be available in a bit.
